- name: Demo on using var on playbooks
  hosts: prod
  vars:                                 ### global variables:can ne accessed by all tasks of the play
    URL: play.google.com
  tasks:
    - name: Printing the var name
      ansible.builtin.debug:
        msg: value of URL is {{ URL }}

  ### If try to print var which is not declared ,it throw error

    - name: Printing local variables
      ansible.builtin.debug:
        msg: value of URL is {{ URL }}
      vars:                           ### local variables: 
          URL: task.google.com


    - name: Printing the var name
      ansible.builtin.debug:
        msg: Name of the car is {{ CARNAME }}

    - name: Demo to show quotes
      ansible.builtin.debug:
        msg: "{{ CARNAME }}"

### CLI Command>>file >>local >> global variables