- name: Demo on using var on playbooks
  hosts: prod
  vars:                                 ### global variables:can ne accessed by all tasks of the play
    URL: play.google.com
  vars_files:
    - dev-vars.yml
  vars_prompt:
    - name: URLName
      prompt: Enter the URL name
  tasks:
    - name: Printing the var name
      ansible.builtin.debug:
        msg: value of URL is {{ URL }}

  ### If try to print var which is not declared ,it throw error

    - name: Printing local variables
      ansible.builtin.debug:
        msg: value of URL is {{ URL }}
      vars:                           ### local variables: 
          URL: task.google.com


    - name: Printing the var name
      ansible.builtin.debug:
        msg: Name of the car is {{ CARNAME }}

    - name: Demo to show quotes
      ansible.builtin.debug:
        msg: "{{ CARNAME }}"

    - name: Prompt variables
      ansible.builtin.debug:
        msg: URL from the prompt variable is {{ URLName }}"

### CLI Command >>local >> file >> global variables