- name: Demo on register module
  hosts: prod
  tasks:
    - name: Demo on the shell module
      ansible.builtin.shell: uptime
      register: OUT 

    - name: Printing the out variable
      ansible.builtin.debug:
        msg: "{{ OUT.stdout }}"

    - name: Declare variable
        set_fact:
          STATUSCODE: "{{ OUT.rc }}"
    
    - name: Priting the uptime 
       ansible.builtin.debug: uptime
         msg: Uptime command exit code is  {{ STATUSCODE }}