- name: Demo on privelege escalation
  hosts: prod
  become: yes
  tasks:
    - name: printing privelege escalation
      ansible.builtin.shell:
      register: OUT 
    - name: printing privelege escalation
      ansible.builtin.debug:
      msg: "{{ OUT.stdout }}" 