- name: Demo on privilege escalation
  hosts: prod
  become: yes
  tasks:
    - name: printing privilege escalation
      ansible.builtin.shell:
      register: OUT 
    - name: printing privilege escalation
      ansible.builtin.debug:
      msg: "{{ OUT.stdout }}" 