- name: Installing nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Downloading and extracting the component
  ansible.builtin.unarchive:
   src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
   dest: /tmp
   remote_src: yes

- name: Cleanup of old HTML content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent
   
- name: Copy the frontend component which is downloaded on the remote machines nignix path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}.main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copying the proxy configuration
  ansible.builtin.copy:
  src: roboshop.conf
  dest: /etc/nginx/default.d/roboshop.conf
   
- name: Starting nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true